# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Gerik/Documents/sha-256/sha-256.cache/wt [current_project]
set_property parent.project_path C:/Users/Gerik/Documents/sha-256/sha-256.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Gerik/Documents/sha-256/sha-256.srcs/sources_1/new/shiftRegister.v
  C:/Users/Gerik/Documents/sha-256/sha-256.srcs/sources_1/new/spiHw.v
  C:/Users/Gerik/Documents/sha-256/sha-256.srcs/sources_1/new/SPICtrlUnit.v
  C:/Users/Gerik/Documents/sha-256/sha-256.srcs/sources_1/new/regFile.v
  C:/Users/Gerik/Documents/sha-256/sha-256.srcs/sources_1/new/designWrapper.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Gerik/Documents/sha-256/sha-256.srcs/constrs_1/new/arty.xdc
set_property used_in_implementation false [get_files C:/Users/Gerik/Documents/sha-256/sha-256.srcs/constrs_1/new/arty.xdc]


synth_design -top designWrapper -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef designWrapper.dcp

catch { report_utilization -file designWrapper_utilization_synth.rpt -pb designWrapper_utilization_synth.pb }
